import type { Libraries, PackageOption } from './types.js';
import { flattenObjectValues } from './helpers.js';
// docs moved into each package option via `docs` field

function linkify(lib?: PackageOption | null): string {
  if (!lib || lib.name === 'none') return 'None';
  const url = lib.docs;
  if (url) return `[${lib.cli.displayName}](${url})`;
  return lib.cli.displayName;
}

function linkifyMany(arr?: PackageOption[] | null): string {
  const list = (arr ?? []).filter(Boolean);
  if (!list.length) return 'None';
  return list.map((lib) => linkify(lib)).join(', ');
}

export function generateReadme(_: string, libs: Libraries, pkgManager: { install: string; run: string }): string {
  const baseLinks = [
    { label: 'Vite', url: 'https://vitejs.dev/' },
    { label: 'React', url: 'https://react.dev/' },
    { label: 'TypeScript', url: 'https://www.typescriptlang.org/' },
    { label: 'Tailwind CSS', url: 'https://tailwindcss.com/' },
    { label: 'SVGR (Vite)', url: 'https://github.com/pd4d10/vite-plugin-svgr' },
    { label: 'TSConfig Paths (Vite)', url: 'https://github.com/aleclarson/vite-tsconfig-paths' },
  ];

  const selectedAll = flattenObjectValues(libs).filter((l) => l && l.name !== 'none');

  const learnLinks = selectedAll
    .map((lib) => ({ label: lib.cli.displayName, url: lib.docs }))
    .filter((x) => Boolean(x.url)) as { label: string; url: string }[];

  const pmInstall = pkgManager.install;
  const pmRun = pkgManager.run;

  return `# React Creative Starter

React Creative Starter generated by \`create-react-creative\`. It uses Vite + React + TypeScript with a few opinionated-DX enhancements, and includes optional libraries you selected below.

## Stack Overview

- Build: [Vite](https://vitejs.dev/) + [TypeScript](https://www.typescriptlang.org/)
- UI: [React](https://react.dev/)
- Styling: [Tailwind CSS](https://tailwindcss.com/)
- DX: [SVGR (Vite)](https://github.com/pd4d10/vite-plugin-svgr), [TSConfig Paths](https://github.com/aleclarson/vite-tsconfig-paths)

### Your Selections

- Animation: ${linkify(libs.animation)}
- State Management: ${linkify(libs.stateManagement)}
- 3D / Graphics: ${linkify(libs.three)}
- R3F Helpers: ${linkifyMany(libs.reactThree)}
- Creative Tools: ${linkifyMany(libs.creative)}

## Getting Started

1. Install dependencies & format 
   \`${pmInstall}\`;\`${pmRun} format\`
2. Start the dev server  
   \`${pmRun} dev\`

## Scripts

- \`${pmRun} dev\` — Start Vite dev server
- \`${pmRun} build\` — Build the app
- \`${pmRun} preview\` — Preview the built app
- \`${pmRun} lint\` — Run ESLint
- \`${pmRun} format\` — Run Prettier

## Learn More

${[...baseLinks, ...learnLinks].map((l) => `- [${l.label}](${l.url})`).join('\n')}

---

Generated with ❤️ by create-react-creative
`;
}
