version: 2
updates:
  # Keep GitHub Actions versions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: dev
    commit-message:
      prefix: 'chore(ci):'
    groups:
      all-actions:
        patterns:
          - '*' # group all action bumps into one PR

  # Keep template dependencies up to date
  - package-ecosystem: npm
    directory: /template/
    schedule:
      interval: weekly
    target-branch: dev
    commit-message:
      prefix: 'chore(deps-template):'
    groups:
      all-template:
        patterns:
          - '*' # group all template deps into one PR
