name: Lint and Format

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: npm-dev-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-dev-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-dev-

      - name: Install dev deps only
        run: npm ci --only=dev --no-audit --no-fund --prefer-offline

      - name: Run Prettier check
        run: npm run format-check

      - name: Run ESLint
        run: npm run lint
