name: Sync engines.node with create-vite

on:
  schedule:
    - cron: '0 2 * * *' # run daily at 2am
  workflow_dispatch:

env:
  UPDATE_BRANCH: update-engines-node
  ACTOR_NAME: ${{ github.actor }}
  ACTOR_EMAIL: ${{ github.actor }}@users.noreply.github.com

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr-url: ${{ steps.cpr.outputs.pull-request-url }}
      pr-number: ${{ steps.cpr.outputs.pull-request-number }}
      node_versions_test: ${{ steps.parse.outputs.node_versions_test }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch create-vite package.json
        run: |
          curl -s https://raw.githubusercontent.com/vitejs/vite/main/packages/create-vite/package.json > "$RUNNER_TEMP/create-vite.json"

      - name: Install runner dependencies
        run: npm ci

      - name: Parse Node engines
        id: parse
        run: |
          node_versions=$(jq -r '.engines.node' "$RUNNER_TEMP/create-vite.json")
          echo "Upstream engines.node = $node_versions"

          # Use semver to extract lowest versions per range
          node_versions_test=$(node -e "
          const semver = require('semver');
          const range = process.argv[1];
          const parts = range.split('||').map(r => r.trim());
          const mins = parts.map(r => semver.minVersion(r).version);
          console.log(JSON.stringify(mins));
          " "$node_versions")

          echo "Lowest versions: $node_versions_test"
          echo "node_versions=$node_versions" >> $GITHUB_OUTPUT
          echo "node_versions_test=$node_versions_test" >> $GITHUB_OUTPUT

      - name: Update package.json if needed
        id: update-file
        run: |
          CURRENT=$(jq -r '.engines.node' package.json)
          NEW="${{ steps.parse.outputs.node_versions }}"
          if [ "$CURRENT" != "$NEW" ]; then
            echo "Updating engines.node from $CURRENT to $NEW"
            jq ".engines.node = \"$NEW\"" package.json > package.json.tmp && mv package.json.tmp package.json
            # Set an output to indicate a change was made
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.update-file.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.UPDATE_BRANCH }}
          commit-message: 'chore: sync engines.node with create-vite (${{ steps.parse.outputs.node_versions }})'
          title: 'chore: sync engines.node with create-vite ${{ steps.parse.outputs.node_versions_test }}'
          body: |
            This PR updates the `engines.node` field in `package.json` to match
            `create-vite`'s latest Node.js requirement.

            **Old version:** `${{ steps.update-file.outputs.old_version }}`
            **New version:** `${{ steps.parse.outputs.node_versions_test }}`

  test:
    runs-on: ubuntu-latest
    needs: sync
    if: needs.sync.outputs.pr-url != ''
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.sync.outputs.node_versions_test) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.UPDATE_BRANCH }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  auto-merge:
    runs-on: ubuntu-latest
    needs: [sync, test]
    if: needs.sync.outputs.pr-url != ''
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ needs.sync.outputs.pr-number }}
          merge-method: squash
