name: Test npm publish (Verdaccio) and semantic release

on:
  pull_request:
    branches: [next, main]
    paths-ignore: [README.md, LICENSE, 'docs/**', '.github/**']
  workflow_dispatch:

jobs:
  test-publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      verdaccio:
        image: verdaccio/verdaccio:6
        ports:
          - 4873:4873

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Dry-run publish to npm.js registry
        run: npm publish --dry-run

      - name: Login to Verdaccio
        run: |
          npx npm-cli-login \
            -u test \
            -p 1234 \
            -e test@domain.test \
            -r http://localhost:4873

      - name: Publish to Verdaccio registry
        run: npm publish
        env:
          npm_config_registry: http://localhost:4873

      - name: Verify package metadata
        run: npm info ${{ github.event.repository.name }} --json
        env:
          npm_config_registry: http://localhost:4873

      - name: Install globally from Verdaccio
        run: npm install -g ${{ github.event.repository.name }}
        env:
          npm_config_registry: http://localhost:4873

      - name: Run publish tests
        run: npm run test:publish
        env:
          npm_config_registry: http://localhost:4873

  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs full history

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npm ci
      - run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
